# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/EmptyLines:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
